function pLn = priorRatioLn(map, knot, idx, delta, hystd)

mapProp = map;
mapProp(idx) = mapProp(idx) + delta;

slpL = (map(idx(1))-map(idx(1)-1))/(knot(idx(1))-knot(idx(1)-1));
slpLProp = (mapProp(idx(1))-mapProp(idx(1)-1))/(knot(idx(1))-knot(idx(1)-1));
if idx(end)~=length(map)
    slpR = (map(idx(end)+1)-map(idx(end)))/(knot(idx(end)+1)-knot(idx(end)));
    slpRProp = (mapProp(idx(end)+1)-mapProp(idx(end)))/(knot(idx(end)+1)-knot(idx(end)));
end

if slpLProp<0.5 || slpLProp>1.5
    pLn = -inf;
elseif idx(end)~=length(map) && (slpRProp<0.5 || slpRProp>1.5)
    pLn = -inf;
else
    if idx(1)==2
        slpLL = 1;
    else
        slpLL = (map(idx(1)-1)-map(idx(1)-2))/(knot(idx(1)-1)-knot(idx(1)-2));
    end
    if numel(idx)==1     % size=1; LL -> L -> R -> RR
        if idx(end)==length(map)
            pLn = -0.5/hystd^2*((slpLProp-slpLL)^2-(slpL-slpLL)^2);
        elseif idx(end)==length(map)-1
            pLn = -0.5/hystd^2*((slpLProp-slpLL)^2+(slpRProp-slpLProp)^2-(slpL-slpLL)^2-(slpR-slpL)^2) ...
                -log(normcdf(1.5,slpLProp,hystd)-normcdf(0.5,slpLProp,hystd)) ...
                +log(normcdf(1.5,slpL,hystd)-normcdf(0.5,slpL,hystd));
        else
            slpRR = (map(idx(end)+2)-map(idx(end)+1))/(knot(idx(end)+2)-knot(idx(end)+1));
            pLn = -0.5/hystd^2*((slpLProp-slpLL)^2+(slpRProp-slpLProp)^2+(slpRR-slpRProp)^2 ...
                -(slpL-slpLL)^2-(slpR-slpL)^2-(slpRR-slpR)^2) ...
                -log(normcdf(1.5,slpLProp,hystd)-normcdf(0.5,slpLProp,hystd)) ... 
                -log(normcdf(1.5,slpRProp,hystd)-normcdf(0.5,slpRProp,hystd)) ...
                +log(normcdf(1.5,slpL,hystd)-normcdf(0.5,slpL,hystd)) ...
                +log(normcdf(1.5,slpR,hystd)-normcdf(0.5,slpR,hystd));
        end
    elseif numel(idx)==2   % size=2; LL -> L -> M -> R -> RR
        slpM = (map(idx(end))-map(idx(1)))/(knot(idx(end))-knot(idx(1)));
        if idx(end)==length(map)
            pLn = -0.5/hystd^2*((slpLProp-slpLL)^2+(slpM-slpLProp)^2-(slpL-slpLL)^2-(slpM-slpL)^2) ...
                -log(normcdf(1.5,slpLProp,hystd)-normcdf(0.5,slpLProp,hystd)) ...
                +log(normcdf(1.5,slpL,hystd)-normcdf(0.5,slpL,hystd));
        elseif idx(end)==length(map)-1
            pLn = -0.5/hystd^2*((slpLProp-slpLL)^2+(slpM-slpLProp)^2+(slpRProp-slpM)^2 ...
                -(slpL-slpLL)^2-(slpM-slpL)^2-(slpR-slpM)^2) ...
                -log(normcdf(1.5,slpLProp,hystd)-normcdf(0.5,slpLProp,hystd)) ...
                +log(normcdf(1.5,slpL,hystd)-normcdf(0.5,slpL,hystd));
        else
            slpRR = (map(idx(end)+2)-map(idx(end)+1))/(knot(idx(end)+2)-knot(idx(end)+1));
            pLn = -0.5/hystd^2*((slpLProp-slpLL)^2+(slpM-slpLProp)^2+(slpRProp-slpM)^2+(slpRR-slpRProp)^2 ...
                -(slpL-slpLL)^2-(slpM-slpL)^2-(slpR-slpM)^2-(slpRR-slpR)^2) ...
                -log(normcdf(1.5,slpLProp,hystd)-normcdf(0.5,slpLProp,hystd)) ...
                -log(normcdf(1.5,slpRProp,hystd)-normcdf(0.5,slpRProp,hystd)) ...
                +log(normcdf(1.5,slpL,hystd)-normcdf(0.5,slpL,hystd)) ...
                +log(normcdf(1.5,slpR,hystd)-normcdf(0.5,slpR,hystd));
        end
    else % size>2; LL -> L -> LR, RL -> R -> RR
        slpLR = (map(idx(1)+1)-map(idx(1)))/(knot(idx(1)+1)-knot(idx(1)));
        slpRL = (map(idx(end))-map(idx(end)-1))/(knot(idx(end))-knot(idx(end)-1));
        if idx(end)==length(map)
            pLn = -0.5/hystd^2*((slpLProp-slpLL)^2+(slpLR-slpLProp)^2-(slpL-slpLL)^2-(slpLR-slpL)^2) ...
                -log(normcdf(1.5,slpLProp,hystd)-normcdf(0.5,slpLProp,hystd)) ...
                +log(normcdf(1.5,slpL,hystd)-normcdf(0.5,slpL,hystd));
        elseif idx(end)==length(map)-1
            pLn = -0.5/hystd^2*((slpLProp-slpLL)^2+(slpLR-slpLProp)^2+(slpRProp-slpRL)^2 ...
                -(slpL-slpLL)^2-(slpLR-slpL)^2-(slpR-slpRL)^2) ...
                -log(normcdf(1.5,slpLProp,hystd)-normcdf(0.5,slpLProp,hystd)) ...
                +log(normcdf(1.5,slpL,hystd)-normcdf(0.5,slpL,hystd));
        else
            slpRR = (map(idx(end)+2)-map(idx(end)+1))/(knot(idx(end)+2)-knot(idx(end)+1));
            pLn = -0.5/hystd^2*((slpLProp-slpLL)^2+(slpLR-slpLProp)^2+(slpRProp-slpRL)^2+(slpRR-slpRProp)^2 ...
                -(slpL-slpLL)^2-(slpLR-slpL)^2-(slpR-slpRL)^2-(slpRR-slpR)^2) ...
                -log(normcdf(1.5,slpLProp,hystd)-normcdf(0.5,slpLProp,hystd)) ...
                -log(normcdf(1.5,slpRProp,hystd)-normcdf(0.5,slpRProp,hystd)) ...
                +log(normcdf(1.5,slpL,hystd)-normcdf(0.5,slpL,hystd)) ...
                +log(normcdf(1.5,slpR,hystd)-normcdf(0.5,slpR,hystd));
        end
    end
end

